[package]
name = "rshell_bash_parser"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "rshell_bash_parser"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.32.0"
tree-sitter = "0.25"
tree-sitter-bash = { path = "../../vendor/tree-sitter-bash" }
